###recuperar peliculas
GET http://localhost:3000/movies

###recuparar pelicula por id
GET http://localhost:3000/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf

###recuperar pelicula por genero
GET http://localhost:3000/movies?genre=Action

###creat una pelicula con post
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title":"good father",
    "year":1975,
    "duration": 175,
    "director":"Francis Ford",
    "poster":"https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Action",
        "Crime"
    ]
}

###Actualizar una pelicula
PATCH http://localhost:3000/movies/62f2c59b-545e-46f4-835f-6071f9fba9d6
Content-Type: application/json

{
    "year":1989
}

###eliminar una pelicula
DELETE http://localhost:3000/movies/62f2c59b-545e-46f4-835f-6071f9fba9d6
Content-Type: application/json